apiVersion: v1
kind: Service
metadata:
  name: skelton-app
spec:
  type: NodePort
  selector:
    app: skelton-app
  ports:
    - port: 4200
      targetPort: 4200
      nodePort: 30021
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skelton-app
  labels:
    app: skelton-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skelton-app
  template:
    metadata:
      labels:
        app: skelton-app
    spec:
      containers:
        - name: skelton-app
          image: rihabbennour/skelton-app:latest
          ports:
            - containerPort: 4200
